destination: ./_site
auto:        true
lsi:         false
server_port: 4000
pygments:    true
markdown:    redcarpet
paginate:    10
exclude:
  - config.rb
  - config.ru
  - Gemfile
  - Gemfile.lock
  - README.md


